import { useState, useEffect } from "react";
import type { DocumentGenerated } from "../../../shared/types";
import type { RenderSnapshot } from "../../documentEngine/lifecycle/types";
import { getLatestSnapshot } from "../../documentEngine/lifecycle/snapshots";
import { diagnoseLifecycle, summariseLifecycleDiagnostics } from "../../documentEngine/lifecycle/validation";

interface LifecycleDiagnosticsProps {
  document: DocumentGenerated;
}

export function LifecycleDiagnostics({ document }: LifecycleDiagnosticsProps) {
  const [snapshot, setSnapshot] = useState<RenderSnapshot | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (document.snapshotId) {
      getLatestSnapshot(document.id).then((s) => {
        setSnapshot(s);
        setLoading(false);
      });
    } else {
      setLoading(false);
    }
  }, [document.id, document.snapshotId]);

  const state = document.lifecycleState ?? 'draft';
  const diagnostics = diagnoseLifecycle(
    {
      lifecycleState: state,
      generatedBy: document.generatedBy,
      issuedAt: state === 'issued' ? document.generatedAt.toISOString() : undefined,
      lastSnapshotId: document.snapshotId,
    },
    snapshot
  );

  const summary = summariseLifecycleDiagnostics(diagnostics);

  return (
    <div className="space-y-3">
      <p className="text-xs font-semibold text-text-tertiary uppercase tracking-wider">Document Lifecycle</p>

      {/* State badge */}
      <div className="flex items-center gap-2">
        <span className={`text-xs px-2 py-0.5 rounded font-medium ${
          state === 'draft' ? 'bg-bg-input text-text-tertiary' :
          state === 'generated' ? 'bg-blue-900/30 text-blue-400' :
          state === 'issued' ? 'bg-indigo-900/30 text-indigo-400' :
          state === 'executed' ? 'bg-green-900/30 text-green-400' :
          state === 'superseded' ? 'bg-amber-900/30 text-amber-400' :
          'bg-red-900/30 text-red-400'
        }`}>{state.toUpperCase()}</span>
        <span className="text-[10px] text-text-tertiary">{summary}</span>
      </div>

      {loading && <p className="text-[10px] text-text-tertiary">Loading snapshot...</p>}

      {snapshot && (
        <div className="border border-border-secondary rounded-lg p-2 space-y-1">
          <p className="text-[10px] text-text-tertiary">Snapshot v{snapshot.snapshotVersion}</p>
          <p className="text-[10px] text-text-tertiary">Schema v{snapshot.schemaVersion} · Transaction v{snapshot.transactionVersion}</p>
          <p className="text-[10px] text-text-tertiary">Sections: {snapshot.sectionIds.length}</p>
          <p className="text-[10px] text-text-tertiary">Generated by: {snapshot.generatedBy}</p>
          <p className="text-[10px] text-text-tertiary">Created: {snapshot.createdAt.toLocaleString()}</p>
        </div>
      )}

      {/* Warnings */}
      {diagnostics.warnings.length > 0 && (
        <details className="text-xs" open>
          <summary className="text-amber-400 cursor-pointer font-medium">
            Warnings ({diagnostics.warnings.length})
          </summary>
          <div className="mt-1 space-y-1 pl-2">
            {diagnostics.warnings.map((w, i) => (
              <p key={i} className="text-[10px] text-amber-400/80">[{w.type}] {w.message}</p>
            ))}
          </div>
        </details>
      )}

      {/* Lineage */}
      <details className="text-xs">
        <summary className="text-text-tertiary cursor-pointer hover:text-text">
          Lineage
        </summary>
        <div className="mt-1 space-y-1 pl-2">
          <p className="text-[10px] text-text-tertiary">Document ID: {document.id}</p>
          <p className="text-[10px] text-text-tertiary">Template: {document.templateName}</p>
          <p className="text-[10px] text-text-tertiary">Project: {document.projectName}</p>
          {document.supersedes && (
            <p className="text-[10px] text-amber-400/80">Supersedes: {document.supersedes}</p>
          )}
          {document.generatedFromId && (
            <p className="text-[10px] text-text-tertiary">Generated from: {document.generatedFromId}</p>
          )}
          {snapshot && (
            <p className="text-[10px] text-green-400">Snapshot integrity: {snapshot.renderedContent ? '✓' : '✗'}</p>
          )}
        </div>
      </details>
    </div>
  );
}
